/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import model.Fin_movimentacaoprodutos;
import model.Pro_produto;

/**
 *
 * @author juliano
 */
public class frmMNotaFiscalEntrada extends javax.swing.JFrame {

    /**
     * Creates new form frmMNotaFiscalEntrada
     */
    public frmMNotaFiscalEntrada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabProPar = new javax.swing.JTabbedPane();
        panelParcelas = new javax.swing.JPanel();
        btnAddPar = new javax.swing.JButton();
        btnEditPar = new javax.swing.JButton();
        btnDelPar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        gridParcelas = new javax.swing.JTable();
        panelProdutos = new javax.swing.JPanel();
        btnDelPro = new javax.swing.JButton();
        btnEditPro = new javax.swing.JButton();
        btnAddPro = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        gridProdutos = new javax.swing.JTable();
        cboCatMovimentacao = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboPessoa = new javax.swing.JComboBox();
        txtNumNota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtNumNota1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumNota2 = new javax.swing.JTextField();
        txtNumNota3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manutenção de Nota Fiscal");

        btnAddPar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAddPar.setText("Adicionar");
        btnAddPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddParActionPerformed(evt);
            }
        });

        btnEditPar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnEditPar.setText("Editar");
        btnEditPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditParActionPerformed(evt);
            }
        });

        btnDelPar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDelPar.setText("Deletar");
        btnDelPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelParActionPerformed(evt);
            }
        });

        gridParcelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vencimento", "Valor Total", "Número do Documento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gridParcelas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        gridParcelas.setName("jTableDados"); // NOI18N
        gridParcelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridParcelasMouseClicked(evt);
            }
        });
        gridParcelas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                gridParcelasPropertyChange(evt);
            }
        });
        gridParcelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gridParcelasKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(gridParcelas);

        javax.swing.GroupLayout panelParcelasLayout = new javax.swing.GroupLayout(panelParcelas);
        panelParcelas.setLayout(panelParcelasLayout);
        panelParcelasLayout.setHorizontalGroup(
            panelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParcelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddPar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditPar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(btnDelPar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParcelasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelParcelasLayout.setVerticalGroup(
            panelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParcelasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditPar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelPar))
                    .addComponent(btnAddPar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(panelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParcelasLayout.createSequentialGroup()
                    .addContainerGap(42, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        tabProPar.addTab("Parcelas", panelParcelas);

        btnDelPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDelPro.setText("Deletar");
        btnDelPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelProActionPerformed(evt);
            }
        });

        btnEditPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnEditPro.setText("Editar");
        btnEditPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProActionPerformed(evt);
            }
        });

        btnAddPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAddPro.setText("Adicionar");
        btnAddPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProActionPerformed(evt);
            }
        });

        gridProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "pro_codigo", "rcd_codigo", "Produto", "Quantidade", "Valor Unit.", "Valor Total", "Desconto", "Valor Bruto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gridProdutos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        gridProdutos.setName("jTableDados"); // NOI18N
        gridProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridProdutosMouseClicked(evt);
            }
        });
        gridProdutos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                gridProdutosPropertyChange(evt);
            }
        });
        gridProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gridProdutosKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(gridProdutos);
        if (gridProdutos.getColumnModel().getColumnCount() > 0) {
            gridProdutos.getColumnModel().getColumn(0).setMinWidth(0);
            gridProdutos.getColumnModel().getColumn(0).setPreferredWidth(0);
            gridProdutos.getColumnModel().getColumn(0).setMaxWidth(0);
            gridProdutos.getColumnModel().getColumn(1).setMinWidth(0);
            gridProdutos.getColumnModel().getColumn(1).setPreferredWidth(0);
            gridProdutos.getColumnModel().getColumn(1).setMaxWidth(0);
            gridProdutos.getColumnModel().getColumn(7).setMinWidth(0);
            gridProdutos.getColumnModel().getColumn(7).setPreferredWidth(0);
            gridProdutos.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        javax.swing.GroupLayout panelProdutosLayout = new javax.swing.GroupLayout(panelProdutos);
        panelProdutos.setLayout(panelProdutosLayout);
        panelProdutosLayout.setHorizontalGroup(
            panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(panelProdutosLayout.createSequentialGroup()
                        .addComponent(btnAddPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditPro, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                        .addComponent(btnDelPro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelProdutosLayout.setVerticalGroup(
            panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelPro))
                    .addComponent(btnAddPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabProPar.addTab("Produtos", panelProdutos);

        cboCatMovimentacao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCatMovimentacaoItemStateChanged(evt);
            }
        });
        cboCatMovimentacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboCatMovimentacaoKeyPressed(evt);
            }
        });

        jLabel4.setText("CATEGORIA MOV.");

        jLabel5.setText("PESSOA");
        jLabel5.setToolTipText("");

        cboPessoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPessoaItemStateChanged(evt);
            }
        });
        cboPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboPessoaKeyPressed(evt);
            }
        });

        txtNumNota.setToolTipText("");
        txtNumNota.setName("txtDesc"); // NOI18N
        txtNumNota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumNotaFocusLost(evt);
            }
        });
        txtNumNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumNotaKeyPressed(evt);
            }
        });

        jLabel3.setText("Nº NOTA");

        jLabel6.setText("OBSERVAÇÃO");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel7.setText("VALOR BRUTO");

        txtNumNota1.setToolTipText("");
        txtNumNota1.setName("txtDesc"); // NOI18N
        txtNumNota1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumNota1FocusLost(evt);
            }
        });
        txtNumNota1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumNota1KeyPressed(evt);
            }
        });

        jLabel8.setText("DESCONTO");

        txtNumNota2.setToolTipText("");
        txtNumNota2.setName("txtDesc"); // NOI18N
        txtNumNota2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumNota2FocusLost(evt);
            }
        });
        txtNumNota2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumNota2KeyPressed(evt);
            }
        });

        txtNumNota3.setToolTipText("");
        txtNumNota3.setEnabled(false);
        txtNumNota3.setName("txtDesc"); // NOI18N
        txtNumNota3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumNota3FocusLost(evt);
            }
        });
        txtNumNota3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumNota3KeyPressed(evt);
            }
        });

        jLabel9.setText("VALOR LIQ.");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton2.setText("SALVAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabProPar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboPessoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboCatMovimentacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumNota)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCatMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNumNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNumNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNumNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabProPar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCatMovimentacaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCatMovimentacaoItemStateChanged

    }//GEN-LAST:event_cboCatMovimentacaoItemStateChanged

    private void cboCatMovimentacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboCatMovimentacaoKeyPressed

    }//GEN-LAST:event_cboCatMovimentacaoKeyPressed

    private void cboPessoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPessoaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPessoaItemStateChanged

    private void cboPessoaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboPessoaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPessoaKeyPressed

    private void txtNumNotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumNotaFocusLost

    }//GEN-LAST:event_txtNumNotaFocusLost

    private void txtNumNotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumNotaKeyPressed

    }//GEN-LAST:event_txtNumNotaKeyPressed

    private void txtNumNota1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumNota1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumNota1FocusLost

    private void txtNumNota1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumNota1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumNota1KeyPressed

    private void txtNumNota2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumNota2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumNota2FocusLost

    private void txtNumNota2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumNota2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumNota2KeyPressed

    private void txtNumNota3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumNota3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumNota3FocusLost

    private void txtNumNota3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumNota3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumNota3KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddParActionPerformed

    }//GEN-LAST:event_btnAddParActionPerformed

    private void btnEditParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditParActionPerformed

    }//GEN-LAST:event_btnEditParActionPerformed

    private void btnDelParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelParActionPerformed

    }//GEN-LAST:event_btnDelParActionPerformed

    private void btnDelProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelProActionPerformed

    private void btnEditProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditProActionPerformed

    private void btnAddProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProActionPerformed
        frmMProdutosNotaFiscal frm = new frmMProdutosNotaFiscal(this, true, null);
        frm.setVisible(true);
        Fin_movimentacaoprodutos mvp_codigo = frm._fin_movimentacaoprodutos;

        DefaultTableModel dados = (DefaultTableModel) gridProdutos.getModel();
        dados.addRow(new String[]{
            "" + mvp_codigo.getPro_codigo().getPro_codigo(),
            "" + mvp_codigo.getRcd_codigo().getRcd_codigo(),
            mvp_codigo.getPro_codigo().getPro_descricao(),
            "" + mvp_codigo.getPro_quantidade(),
            "" + mvp_codigo.getPro_valorunitario(),
            "" + mvp_codigo.getPro_valorliquido(),
            "" + mvp_codigo.getPro_desconto(),
            "" + mvp_codigo.getPro_valorbruto()
        });
    }//GEN-LAST:event_btnAddProActionPerformed

    private void gridParcelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridParcelasMouseClicked

    }//GEN-LAST:event_gridParcelasMouseClicked

    private void gridParcelasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_gridParcelasPropertyChange

    }//GEN-LAST:event_gridParcelasPropertyChange

    private void gridParcelasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gridParcelasKeyPressed

    }//GEN-LAST:event_gridParcelasKeyPressed

    private void gridProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridProdutosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gridProdutosMouseClicked

    private void gridProdutosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_gridProdutosPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_gridProdutosPropertyChange

    private void gridProdutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gridProdutosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_gridProdutosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMNotaFiscalEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMNotaFiscalEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMNotaFiscalEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMNotaFiscalEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMNotaFiscalEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPar;
    private javax.swing.JButton btnAddPro;
    private javax.swing.JButton btnDelPar;
    private javax.swing.JButton btnDelPro;
    private javax.swing.JButton btnEditPar;
    private javax.swing.JButton btnEditPro;
    private javax.swing.JComboBox cboCatMovimentacao;
    private javax.swing.JComboBox cboPessoa;
    private javax.swing.JTable gridParcelas;
    private javax.swing.JTable gridProdutos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelParcelas;
    private javax.swing.JPanel panelProdutos;
    private javax.swing.JTabbedPane tabProPar;
    private javax.swing.JTextField txtNumNota;
    private javax.swing.JTextField txtNumNota1;
    private javax.swing.JTextField txtNumNota2;
    private javax.swing.JTextField txtNumNota3;
    // End of variables declaration//GEN-END:variables
}
